---
name: Renovate lint

on:
  pull_request:
    paths:
      - '.github/workflows/renovatelint.yml'
      - '**/renovate.json'

concurrency:
  cancel-in-progress: true
  group: ${{ format('{0}-{1}', github.workflow, github.ref) }}

permissions:
  contents: read

jobs:
  renovate-config-validator:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/renovatebot/renovate@sha256:04a60fea88f50d31158902c24553fae748e97d5e1d7524ad7d6c69b874650065 # 43.141.2
      options: --user root
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: renovate-config-validator --strict .github/renovate.json
