---
name: Renovate lint

on:
  pull_request:
    paths:
      - '.github/workflows/renovatelint.yml'
      - '**/renovate.json'

concurrency:
  cancel-in-progress: true
  group: ${{ format('{0}-{1}', github.workflow, github.ref) }}

permissions:
  contents: read

jobs:
  renovate-config-validator:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/renovatebot/renovate@sha256:29118bc0bfe3fd231c246c22b648a063862c11e70d3b15cf18c7094a9f4fc455 # 43.141.2
      options: --user root
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - run: renovate-config-validator --strict .github/renovate.json
